[package]
name = "owm-rs"
version = "1.0.12"
edition = "2021"
authors = ["Oscuro87"]
repository = "https://github.com/Oscuro87/owm-rs"
description = "Wrapper around the free offer of the OpenWeatherMap API."
license = "MIT"

[features]
utils = []

[[example]]
name = "basic"
required-features = ["utils"]

[dependencies]
tokio = { version = "1.26.0", features = ["full"] }
reqwest = { version = "0.11.14", features = ["json"] }
serde = { version = "1.0.154", features = ["derive"] }

[dev-dependencies]
dotenvy = "0.15.6"
