[package]
name = "owm-rs"
version = "1.0.0"
edition = "2021"
author = ["Oscuro87"]
repository = "https://github.com/Oscuro87/owm-rs"

[features]

[dependencies]
# Send calls and receive response
tokio = { version = "1.21.2", features = ["full"] }
reqwest = { version = "0.11.12", features = ["json"]}
# Parse the response from the API
serde = { version = "1.0.145", features = ["derive"] }

[dev-dependencies]
ron = "0.8.0"
